In [5]:
import pandas as pd
import numpy as np

In [6]:
df = pd.read_csv("food_items_list_with_macros.csv")
df.head(5)

,brand,product_name,base_price,product_size,price_per_unit,unit_price_value,unit_measure,item,protein,carbs,fats
0,no name,"eggs, large",4.16,12 ea,$0.35/1ea,0.35,1ea,eggs,13g/2ea,1g/2ea,11g/2ea
1,no name,grade a large brown eggs,5.37,12 ea,$0.45/1ea,0.45,1ea,eggs,7g/2ea,1g/2ea,6g/2ea
2,burnbrae farms,naturegg simply egg whites,5.39,1 ea,$1.08/100ml,1.08,100ml,eggs,7g/96ml,1g/96ml,0/96ml
3,burnbrae farms,"naturegg nest laid white eggs, large",5.69,12 ea,$0.47/1ea,0.47,1ea,eggs,13g/2ea,1g/2ea,11g/2ea
4,pc organics,free range large brown eggs,7.99,12 ea,$0.67/1ea,0.67,1ea,eggs,13g/2ea,1g/2ea,11/2ea

In [7]:
df = df.replace(np.nan, 'unknown')
df['product_size'] = df['product_size'].str.replace("ea", "eggs")
df['product_size'] = df['product_size'].str.replace("$6.61/1kg", "2.35 kg")
df['product_size'] = df['product_size'].str.replace("12x100.0 g", "Pack of 12 yogurts, each 100g")
df['unit_measure'] = df['unit_measure'].str.replace("1ea", "egg")
df['protein'] = df['protein'].str.replace("7g39g", "7g/39g")
df[['protein', 'macro_weight']] = df['protein'].str.split('/', expand=True)
df['carbs'] = df['carbs'].str.split('/').str[0]
df['fats'] = df['fats'].str.split('/').str[0]

for col in ['protein', 'carbs', 'fats']:
    df[col] = df[col].astype(str).str.replace(r'(?<!g)$', 'g', regex=True)
df['macro_weight'] = df['macro_weight'].str.replace("2ea", "2 eggs")

In [8]:
df["text"] = (
    "Brand is " + df['brand'] + ". " +
    "Product is " + df['product_name'] + ". " +
    "Base Price is $" + df['base_price'].astype(str) + ". " +
    "Size is " + df['product_size'] + ". " +
    "Unit Price is $" + df['unit_price_value'].astype(str) + " per " + df['unit_measure'] + ". " +
    "It contains " + df['protein'] + " of protein, " + df['carbs'] + " of carbs, and " + df['fats'] + " of fats per " + df['macro_weight'] + "."
)

In [10]:
df.head(3)

,brand,product_name,base_price,product_size,price_per_unit,unit_price_value,unit_measure,item,protein,carbs,fats,macro_weight,text
0,no name,"eggs, large",4.16,12 eggs,$0.35/1ea,0.35,egg,eggs,13g,1g,11g,2 eggs,"Brand is no name. Product is eggs, large. Base..."
1,no name,grade a large brown eggs,5.37,12 eggs,$0.45/1ea,0.45,egg,eggs,7g,1g,6g,2 eggs,Brand is no name. Product is grade a large bro...
2,burnbrae farms,naturegg simply egg whites,5.39,1 eggs,$1.08/100ml,1.08,100ml,eggs,7g,1g,0g,96ml,Brand is burnbrae farms. Product is naturegg s...

In [9]:
print(df['text'][0])  # First row
print(df['text'][14]) # Fifteenth row

Brand is no name. Product is eggs, large. Base Price is $4.16. Size is 12 eggs. Unit Price is $0.35 per egg. It contains 13g of protein, 1g of carbs, and 11g of fats per 2 eggs.
Brand is president's choice. Product is free from lean ground beef. Base Price is $9.0. Size is 454 g. Unit Price is $1.98 per 100g. It contains 20g of protein, 0g of carbs, and 13g of fats per 100g.

In [11]:
df.to_csv("food_items_list_cleaned.csv", index=False)